import{useState}from"react"
import{FEATURES}from"../config"
export default function Dashboard(){const[auth,setAuth]=useState(sessionStorage.getItem("ms_dash")==="1"),[pw,setPw]=useState(""),[err,setErr]=useState("")
if(!auth)return<div className="page" style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",minHeight:"100vh"}}><h2 style={{fontSize:18,fontWeight:700,marginBottom:16}}>Dashboard</h2><input className="input" type="password" placeholder="Password" value={pw} onChange={e=>setPw(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){pw==="CivicStack2026!"?(sessionStorage.setItem("ms_dash","1"),setAuth(true)):setErr("Wrong")}}} style={{maxWidth:300,textAlign:"center"}}/><button className="cta" onClick={()=>pw==="CivicStack2026!"?(sessionStorage.setItem("ms_dash","1"),setAuth(true)):setErr("Wrong")} style={{maxWidth:300,marginTop:8}}>Login</button>{err&&<p style={{color:"var(--orange)",marginTop:8,fontSize:13}}>{err}</p>}</div>
return<div className="page" style={{paddingTop:20,paddingBottom:40}}>
{!FEATURES.supabaseEnabled&&<div style={{background:"var(--orange-bg)",border:"1px solid #fecaca",borderRadius:8,padding:12,marginBottom:16,fontSize:13,color:"var(--orange)"}}>Supabase not connected. Demo data.</div>}
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:20}}>{[{l:"Revenue",v:"£0"},{l:"Scans",v:"0"},{l:"Purchases",v:"0"},{l:"Conversion",v:"0%"}].map(m=><div key={m.l} style={{background:"var(--bg-off)",borderRadius:"var(--radius)",padding:16,textAlign:"center"}}><div style={{fontSize:11,color:"var(--text-light)",marginBottom:4}}>{m.l}</div><div style={{fontSize:24,fontWeight:700,color:"var(--navy)"}}>{m.v}</div></div>)}</div>
<div style={{background:"var(--bg-off)",borderRadius:"var(--radius)",padding:16}}><div style={{fontSize:13,fontWeight:600,marginBottom:10}}>System</div>
{[{n:"Website",s:true},{n:"Supabase",s:FEATURES.supabaseEnabled},{n:"Stripe",s:FEATURES.stripeEnabled},{n:"Resend",s:FEATURES.resendEnabled},{n:"Claude API",s:FEATURES.claudeApiEnabled}].map(s=><div key={s.n} style={{display:"flex",justifyContent:"space-between",marginBottom:6,fontSize:13}}><span>{s.n}</span><span style={{color:s.s?"var(--green)":"var(--orange)"}}>{s.s?"Live":"Pending"}</span></div>)}</div></div>}
