import{useState}from"react"
import{useNavigate}from"react-router-dom"
import{loadScan,getSavedEmail,formatMoney}from"../utils/helpers"
const fields={"Car Finance Compensation":[{k:"lender",l:"Finance company",p:"e.g. Black Horse"},{k:"year",l:"Year of agreement",p:"e.g. 2018"}],"Unprotected Deposit":[{k:"landlord",l:"Landlord/agent name",p:""},{k:"amount",l:"Deposit amount",p:"e.g. 1200"}],"Parking Fine Appeal":[{k:"pcn",l:"PCN number",p:"From the ticket"},{k:"date",l:"Date of fine",p:"e.g. 15 March 2026"}],"Marriage Allowance":[{k:"spouse",l:"Spouse name",p:""},{k:"ni",l:"Spouse NI number",p:"e.g. QQ 12 34 56 C"}],"Rent Repayment Order":[{k:"landlord",l:"Landlord name",p:""},{k:"rent",l:"Monthly rent",p:"e.g. 650"}]}
export default function Details(){const nav=useNavigate(),scan=loadScan(),[d,setD]=useState({name:"",email:getSavedEmail(),address:""}),[skip,setSkip]=useState({}),[done,setDone]=useState(false)
if(!scan){nav("/");return null}
const{claims}=scan,upd=(k,v)=>setD(p=>({...p,[k]:v}))
if(done)return<div className="page" style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",minHeight:"80vh",textAlign:"center"}}><div style={{fontSize:40,marginBottom:12}}>✓</div><h2 style={{fontSize:20,fontWeight:700,color:"var(--green)",marginBottom:8}}>Generating your letters...</h2><p style={{fontSize:14,color:"var(--text-mid)"}}>Check your email in 2 minutes.</p></div>
return<div className="page" style={{paddingTop:24,paddingBottom:40}}><h1 style={{fontSize:20,fontWeight:700,marginBottom:4}}>Personalise your letters</h1><p style={{fontSize:13,color:"var(--text-mid)",marginBottom:20}}>Fill in what you can. Skip anything you do not have handy.</p>
<div style={{marginBottom:16}}><label style={{fontSize:13,fontWeight:600,display:"block",marginBottom:4}}>Full name *</label><input className="input" placeholder="Your full legal name" value={d.name} onChange={e=>upd("name",e.target.value)}/></div>
<div style={{marginBottom:16}}><label style={{fontSize:13,fontWeight:600,display:"block",marginBottom:4}}>Email</label><input className="input" placeholder="your@email.com" value={d.email} onChange={e=>upd("email",e.target.value)} type="email"/></div>
<div style={{marginBottom:24}}><label style={{fontSize:13,fontWeight:600,display:"block",marginBottom:4}}>Address</label><textarea className="input" rows={3} placeholder="Full postal address" value={d.address} onChange={e=>upd("address",e.target.value)} style={{resize:"vertical"}}/></div>
{claims.map(c=>{const f=fields[c.category]||[];if(!f.length)return null;return<div key={c.id} style={{marginBottom:16,padding:16,border:"1px solid var(--border)",borderRadius:"var(--radius)",opacity:skip[c.id]?.5:1}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><div style={{display:"flex",alignItems:"center",gap:8}}><div className="claim-icon" style={{background:c.color,width:28,height:28,fontSize:10}}>{c.abbr}</div><span style={{fontSize:14,fontWeight:600}}>{c.category}</span></div>
<span style={{fontSize:12,color:"var(--green)",cursor:"pointer"}} onClick={()=>setSkip(p=>({...p,[c.id]:!p[c.id]}))}>{skip[c.id]?"Add":"Skip"}</span></div>
{!skip[c.id]&&f.map(fi=><div key={fi.k} style={{marginBottom:10}}><label style={{fontSize:12,fontWeight:500,display:"block",marginBottom:3,color:"var(--text-mid)"}}>{fi.l}</label><input className="input" style={{fontSize:14,padding:10}} placeholder={fi.p} value={d[c.id+"_"+fi.k]||""} onChange={e=>upd(c.id+"_"+fi.k,e.target.value)}/></div>)}</div>})}
<button className="cta" onClick={()=>{if(!d.name)return;localStorage.setItem("ms_details",JSON.stringify(d));setDone(true);setTimeout(()=>nav("/letters"),1500)}}>Generate my letters</button>
<div className="trust-footer">Your data is encrypted and never shared.</div></div>}
