import{useState}from"react"
import{useNavigate}from"react-router-dom"
import{loadScan,formatMoney,getOrCreateRefCode,clearScan}from"../utils/helpers"
function gen(c,d){const n=d?.name||"[YOUR NAME]",a=d?.address||"[YOUR ADDRESS]",dt=new Date().toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"});const t={"Car Finance Compensation":n+"\n"+a+"\n\n"+dt+"\n\nDear Sir/Madam,\n\nRe: Complaint regarding discretionary commission\n\nI formally complain about commission on my motor finance agreement. Following FCA PS26/3 (30 March 2026), I believe I am entitled to compensation.\n\n12.1 million agreements eligible. Average compensation £829. I request you process my complaint before 30 June 2026.\n\nYours faithfully,\n"+n,"Unprotected Deposit":n+"\n"+a+"\n\n"+dt+"\n\nDear Sir/Madam,\n\nRe: Failure to protect deposit\n\nUnder Housing Act 2004, landlords must protect deposits within 30 days. I have not received evidence of protection. Under Section 214, I may be entitled to 1-3x compensation.\n\nYours faithfully,\n"+n,"Parking Fine Appeal":n+"\n"+a+"\n\n"+dt+"\n\nDear Sir/Madam,\n\nRe: Formal appeal\n\nI appeal this PCN under the Protection of Freedoms Act 2012 and BPA Code of Practice.\n\nYours faithfully,\n"+n};return t[c.category]||n+"\n"+a+"\n\n"+dt+"\n\nDear Sir/Madam,\n\nRe: "+c.category+"\n\nI am writing regarding my eligibility for "+c.category+", estimated at "+formatMoney(c.amount)+".\n\nYours faithfully,\n"+n}
export default function Letters(){const nav=useNavigate(),scan=loadScan(),[copiedId,setCopiedId]=useState(null);let d={};try{d=JSON.parse(localStorage.getItem("ms_details")||"{}")}catch{}
if(!scan){nav("/");return null}
const{total,claims}=scan,ref=getOrCreateRefCode(),refLink='https://moneyscan.app/?ref='+ref
return<div className="page" style={{paddingTop:24,paddingBottom:40}}>
<div style={{textAlign:"center",marginBottom:24}}><h1 style={{fontSize:20,fontWeight:700,marginBottom:4}}>Your letters are ready.</h1><p style={{fontSize:14,color:"var(--text-mid)"}}>{claims.length} letters for {d.name||"you"}.</p></div>
{claims.map(c=>{const txt=gen(c,d);return<div key={c.id} style={{marginBottom:16,border:"1px solid var(--border)",borderRadius:"var(--radius)",overflow:"hidden"}}>
<div style={{display:"flex",alignItems:"center",gap:10,padding:14,background:"var(--bg-off)"}}><div className="claim-icon" style={{background:c.color,width:32,height:32}}>{c.abbr}</div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600}}>{c.category}</div><div style={{fontSize:12,color:"var(--text-light)"}}>~{formatMoney(c.amount)}</div></div></div>
<div style={{padding:14,fontSize:12,lineHeight:1.7,whiteSpace:"pre-wrap",fontFamily:"monospace",maxHeight:200,overflow:"auto"}}>{txt}</div>
<div style={{padding:10,display:"flex",gap:8,borderTop:"1px solid var(--border)"}}><button className="copy-btn" style={{flex:1,fontSize:12}} onClick={()=>{navigator.clipboard?.writeText(txt);setCopiedId(c.id);setTimeout(()=>setCopiedId(null),2000)}}>{copiedId===c.id?"Copied":"Copy"}</button><button className="copy-btn" style={{flex:1,fontSize:12}} onClick={()=>window.print()}>Print</button></div></div>})}
<div className="share-section" style={{marginTop:24}}><h3>Help others claim</h3><a className="wa-btn" href={"https://wa.me/?text="+encodeURIComponent("I got claim letters from MoneyScan — found "+formatMoney(total)+" I was owed. Check yours: "+refLink)} target="_blank" rel="noopener">Share on WhatsApp</a></div>
<div style={{textAlign:"center",margin:"16px 0"}}><span style={{fontSize:13,color:"var(--green)",cursor:"pointer",fontWeight:600}} onClick={()=>{clearScan();nav("/")}}>Scan for someone else →</span></div></div>}
